spring:
  application:
    name: cm-coding-challenge
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
bundesbank:
  base-url: https://api.statistiken.bundesbank.de/rest
